ALTER TABLE MARK DROP CONSTRAINT MARK_STUDENT_ID_FKEY;
ALTER TABLE MARK DROP CONSTRAINT MARK_SUBJECT_ID_FKEY;
ALTER TABLE MARK ADD CONSTRAINT MARK_STUDENT_ID_FKEY FOREIGN KEY (student_id) REFERENCES student(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE MARK ADD CONSTRAINT MARK_SUBJECT_ID_FKEY FOREIGN KEY (subject_id) REFERENCES subject(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PAYMENT DROP CONSTRAINT PAYMENT_TYPE_ID_FKEY;
ALTER TABLE PAYMENT DROP CONSTRAINT PAYMENT_STUDENT_ID_FKEY;
ALTER TABLE PAYMENT ADD CONSTRAINT PAYMENT_TYPE_ID_FKEY FOREIGN KEY (type_id) REFERENCES paymenttype(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PAYMENT ADD CONSTRAINT PAYMENT_STUDENT_ID_FKEY FOREIGN KEY (student_id) REFERENCES student(id) ON DELETE CASCADE ON UPDATE CASCADE;